trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'

jobs:
- job: DeployNM
  displayName: 'Deploy Axway anm using Bicep'
  steps:
    - task: AzureCLI@2
      displayName: 'Deploy anm with Bicep'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Define parameters
          $resourceGroupName = 'RG-mavishnoi'
          $location = 'northeurope'
          $environmentname = 'testcontainerappenv1'
          
          # Create the resource group if it doesn't exist
          #az group create --name $resourceGroupName --location $location

          az containerapp env create --name $environmentname --resource-group $resourceGroupName --location $location --enable-workload-profiles false -s '/subscriptions/9436480f-c708-4e0f-aba3-3d5af128e84a/resourceGroups/RG-mavishnoi/providers/Microsoft.Network/virtualNetworks/Test/subnets/Test'
          # Deploy the ACR using Bicep
          az deployment group create `
            --resource-group $resourceGroupName `
            --template-file './anm.bicep' `
            --parameters acrName='axwaymanishdevops' containerAppName='my-anm-bicep' imageName='anm' managedEnvironmentName=$environmentname transport=tcp targetPort=8090 acrPassword=IiWYpSG6Cb9Xzl1fyBG5X/gCcoLM+eb0ryxz1owI1y+ACRAqR5xL
