trigger:
  branches:
    include:
      - main
pool:
  name: 'Default'

jobs:
- job: DeployNM
  displayName: 'Deploy Axway anm using Bicep'
  steps:
    - task: Bash@3
      inputs:
       targetType: 'inline'
       script: |
          wget https://www.python.org/ftp/python/3.11.5/python-3.11.5-amd64.exe -O python-installer.exe ./python-installer.exe /quiet InstallAllUsers=1 PrependPath=1
          az upgrade --yes
          az extension add --name containerapp --yes
          az extension update --name containerapp
    - task: AzureCLI@2
      displayName: 'Deploy anm with Bicep'
      inputs:
        azureSubscription: 'axwaymanishdepops1'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Define parameters
          $resourceGroupName = 'RG-mavishnoi'
          $location = 'northeurope'
          $environmentname = 'testcontainerappenv'
          
          # Create the resource group if it doesn't exist
          #az group create --name $resourceGroupName --location $location

          az containerapp env create --name $environmentname --resource-group $resourceGroupName --location $location --vnet Test --subnet Test --environment-type Consumption
          # Deploy the ACR using Bicep
          az deployment group create `
            --resource-group $resourceGroupName `
            --template-file './anm.bicep' `
            --parameters acrName='axwaymanishdevops' containerAppName='my-anm-bicep' imageName='anm' managedEnvironmentName=$environmentname targetPort=8090 acrPassword=IiWYpSG6Cb9Xzl1fyBG5X/gCcoLM+eb0ryxz1owI1y+ACRAqR5xL
